/* The one way the MCP changes a profile: read {state, rev} from the api, apply a pure mutation,
   check the result, write it back conditionally, journal what changed.

   One write at a time (a promise chain), so two tool calls never race each other. A 409 — a
   phone or a browser wrote in between — re-applies the same mutation to the document the api
   sent back, a few times with jitter. Mutations must be deterministic given their inputs: any
   new id is generated by the tool before it calls commit(), never inside the mutation, so a
   retry can never log the same thing twice. */
import { ConflictError } from './api-client.js'
import { diffState, summarize } from './journal.js'
import { checkInvariants } from './invariants.js'

const clone = o => JSON.parse(JSON.stringify(o))
const sleep = ms => new Promise(r => setTimeout(r, ms))

export function toolError(code, message) {
  const e = new Error(message)
  e.code = code
  return e
}

export function createWriter({ client, journal, maxAttempts = 4 }) {
  let chain = Promise.resolve()

  async function attempt(op, mutate, { reason, undoes, requestId, meta }) {
    // Idempotent on request: the same request_id again answers with the change it already made.
    const seen = journal.byRequest(requestId)
    if (seen) return { changed: false, duplicate: true, change_id: seen.id, rev: seen.rev, meta: seen.meta }
    let { state, rev } = await client.read()
    if (!state) throw toolError('ENOSTATE', 'this profile has no synced data yet — sign in once from the app so there is a document to change')
    for (let i = 0; i < maxAttempts; i++) {
      const before = clone(state)
      const after = mutate(clone(state)) || null
      if (!after) throw toolError('EINTERNAL', `${op} produced no document`)
      const patches = diffState(before, after)
      if (!patches.length) return { changed: false, rev }
      checkInvariants(after, patches)
      // Newest on every merge rule that goes by `_ts` (frontend/src/lib/sync-merge.js), so a phone
      // that pushes an older copy on top of this merges instead of winning outright.
      after._ts = Math.max(Date.now(), (before._ts || 0) + 1)
      try {
        const res = await client.write(after, rev, op)
        const entry = journal.record({ op, reason, rev: res.rev, patches, undoes, requestId, meta })
        return { changed: true, change_id: entry.id, rev: res.rev, changes: summarize(patches) }
      } catch (e) {
        if (!(e instanceof ConflictError) || !e.state) throw e
        state = e.state
        rev = e.rev
        await sleep(50 + Math.floor(Math.random() * 200))
      }
    }
    throw toolError('ECONFLICT', 'the profile kept changing while this was being written — try again')
  }

  return {
    journal,
    // Read-only view for tools that need to look before they change (validation messages, ids).
    read: () => client.read(),
    commit(op, mutate, opts = {}) {
      const run = chain.then(() => attempt(op, mutate, opts))
      chain = run.catch(() => {})
      return run
    }
  }
}
